### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by renta75** [longseespace/tey#4]
**Hi,
I tried this example of React-QML and I am sad that sample is not working.
From the server side, everything is OK, but launcher does not launch application.
I have tried on Mac and Linux also, same problem.
Here is the log of laucher execution:**

QML debugging is enabled. Only use this in a safe environment.
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.67 ms
qml: HMR WebSocker connected: ws://localhost:8081/hot
qml: [Haul HMR] Client connected
qml: TypeError: Property 'default' of object [object Object] is not a function

**Comment by longseespace** [comment]
I assume there is no other log messages. Also can you provide the following info:
- Which Qt version are you using to build?
- Which `branch` did you clone from?
- Did you run on dev mode or production mode?

That particular error is from this code https://github.com/longseespace/ben/blob/0471b795d6f76a1321bebe9df40e50ec4d38cc60/src/index.osx.qml#L20

Can you print out the `JS.Bundle` object to see what properties does it have.
```
console.log('JS.Bundle', JSON.stringify(JS.Bundle));
```

Also it's weird that you can run this on Linux. Which OS/distro are you using?
